MvcCoreCrudDepartamentosEF/Models/Departamento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreCrudDepartamentosEF.Models
{
    [Table("DEPT")]
    public class Departamento
    {
        //COMO REALIZAMOS CONSULTAS DE ACCION
        //DEBEMOS PONER DE FORMA OBLIGATORIA LA 
        //DECORACION [Key]
        [Key]
        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }
        [Column("DNOMBRE")]
        public string Nombre { get; set; }
        [Column("LOC")]
        public string Localidad { get; set; }
    }
}

MvcCoreCrudDepartamentosEF/Models/ErrorViewModel.cs
namespace MvcCoreCrudDepartamentosEF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreCrudDepartamentosEF/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreCrudDepartamentosEF.Models;
using MvcCoreCrudDepartamentosEF.Repositories;

namespace MvcCoreCrudDepartamentosEF.Controllers
{
    public class DepartamentosController : Controller
    {
        private RepositoryDepartamentos repo;

        public DepartamentosController(RepositoryDepartamentos repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Departamento> departamentos =
                this.repo.GetDepartamentos();
            return View(departamentos);
        }

        public IActionResult Details(int iddepartamento)
        {
            Departamento departamento =
                this.repo.FindDepartamento(iddepartamento);
            return View(departamento);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Departamento departamento)
        {
            await this.repo.InsertDepartamentoAsync
                (departamento.IdDepartamento, departamento.Nombre
                , departamento.Localidad);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int iddepartamento)
        {
            Departamento departamento = this.repo.FindDepartamento(iddepartamento);
            return View(departamento);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Departamento departamento)
        {
            await this.repo.UpdateDepartamentoAsync
                (departamento.IdDepartamento, departamento.Nombre
                , departamento.Localidad);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int iddepartamento)
        {
            await this.repo.DeleteDepartamentoAsync(iddepartamento);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreCrudDepartamentosEF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreCrudDepartamentosEF.Models;
using System.Diagnostics;

namespace MvcCoreCrudDepartamentosEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreCrudDepartamentosEF/Views/Departamentos/Create.cshtml
<h1>Create</h1>

<form method="post">
    <label>Id departamento</label>
    <input type="text" name="iddepartamento"
        class="form-control" required/>
    <label>Nombre: </label>
    <input type="text" name="nombre"
        class="form-control" required/>
    <label>Localidad: </label>
    <input type="text" name="localidad"
        class="form-control" required/>
    <button class="btn btn-outline-dark">
        Create
    </button>
</form>

MvcCoreCrudDepartamentosEF/Views/Departamentos/Details.cshtml
@model Departamento

<h1>Details</h1>

<ul class="list-group">
    <li class="list-group-item">
        Id Departamento: @Model.IdDepartamento
    </li>
    <li class="list-group-item">
        Nombre: @Model.Nombre
    </li>
    <li class="list-group-item">
        Localidad: @Model.Localidad
    </li>
</ul>

MvcCoreCrudDepartamentosEF/Views/Departamentos/Edit.cshtml
@model Departamento

<h1>Edit</h1>

<form method="post">
    <input type="hidden" name="iddepartamento"
        value="@Model.IdDepartamento"/>
    <label>Nombre: </label>
    <input type="text" name="nombre"
        value="@Model.Nombre" class="form-control" required/>
    <label>Localidad: </label>
    <input type="text" name="localidad"
        value="@Model.Localidad" class="form-control" required/>
    <button class="btn btn-outline-warning">
        Update
    </button>
</form>

MvcCoreCrudDepartamentosEF/Views/Departamentos/Index.cshtml
@model List<Departamento>

<h1>
    Departamentos CRUD EF
</h1>
<p>
    <a asp-controller="Departamentos"
        asp-action="Create">
        Create New
    </a>
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Localidad</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Departamento dept in Model)
        {
            <tr>
                <td>@dept.Nombre</td>
                <td>@dept.Localidad</td>
                <td>
                    <a asp-controller="Departamentos"
                        asp-action="Details"
                        asp-route-iddepartamento="@dept.IdDepartamento"
                        class="btn btn-outline-info">
                        Details
                    </a>
                    <a asp-controller="Departamentos"
                        asp-action="Edit"
                        asp-route-iddepartamento="@dept.IdDepartamento"
                        class="btn btn-info">
                        Edit
                    </a>
                    <a asp-controller="Departamentos"
                        asp-action="Delete"
                        asp-route-iddepartamento="@dept.IdDepartamento"
                        class="btn btn-danger">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcCoreCrudDepartamentosEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreCrudDepartamentosEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreCrudDepartamentosEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreCrudDepartamentosEF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/wolverine.jpg" style="width: 40px"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                                asp-controller="Departamentos" 
                                asp-action="Index">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                asp-controller="Departamentos" 
                                asp-action="Create">
                                Create New
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreCrudDepartamentosEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>